"""empty message

Revision ID: c92c9454227d
Revises: 516fb7716495
Create Date: 2022-02-06 14:57:40.040757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92c9454227d'
down_revision = '516fb7716495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url')
    # ### end Alembic commands ###
