"""empty message

Revision ID: c095cdabcba3
Revises: c92c9454227d
Create Date: 2022-02-06 16:15:02.676767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c095cdabcba3'
down_revision = 'c92c9454227d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.drop_column('users', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
