"""empty message

Revision ID: 516fb7716495
Revises: 9d854020060b
Create Date: 2022-01-12 13:05:51.580891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516fb7716495'
down_revision = '9d854020060b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
