"""empty message

Revision ID: 34a182eaeae5
Revises: 5fddfaebc332
Create Date: 2022-02-24 23:30:11.267238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a182eaeae5'
down_revision = '5fddfaebc332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_receiver_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_receiver_id_fkey', 'messages', 'images', ['receiver_id'], ['id'])
    # ### end Alembic commands ###
